### ISSUE TITLE
could you please add a bit of docs to the readme?

### ISSUE THREAD

**Issue by jexp** [SermoDigital/neograph#2]
Thanks ! 👍

**Comment by ericlagergren** [comment]
Yep! The gist of it is it works as a glue layer between a client and neo4j, safely translating structured JSON (or protobufs) into Cypher. It's separated into Read, Merge, and Create queries and by using structured JSON/protobufs the backend client can edit the query without having to parse any Cypher.

**Comment by ericlagergren** [comment]
It can also function as the base of an ORM—if somebody goes that route they'd have to write something like:

```
type Query struct { ... }

func NewQuery( ... ) *Query { ... }

// Match sets the Query's matching criteria based on the provided (perhaps named) pattern.
func (q *Query) Match(pattern *Vertex, name string, opt bool) *Query {
    // append graphpb.Match to Query
    ...
}

// Cypher returns the generated Cypher query, its arguments, and an error, if any.
func (q *Query) Cypher() (string, args, error)
    return QueryArgs( ... )
}
```

**Comment by jexp** [comment]
Thank you !

**Comment by ericlagergren** [comment]
@jexp you're welcome! I clarified them a bit and added sample JavaScript.
